// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: sports/sports.proto

package sports

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is derived from advertised_start_time: OPEN (future) or CLOSED (past)
type Event_Status int32

const (
	Event_STATUS_OPEN   Event_Status = 0
	Event_STATUS_CLOSED Event_Status = 1
)

// Enum value maps for Event_Status.
var (
	Event_Status_name = map[int32]string{
		0: "STATUS_OPEN",
		1: "STATUS_CLOSED",
	}
	Event_Status_value = map[string]int32{
		"STATUS_OPEN":   0,
		"STATUS_CLOSED": 1,
	}
)

func (x Event_Status) Enum() *Event_Status {
	p := new(Event_Status)
	*p = x
	return p
}

func (x Event_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_sports_sports_proto_enumTypes[0].Descriptor()
}

func (Event_Status) Type() protoreflect.EnumType {
	return &file_sports_sports_proto_enumTypes[0]
}

func (x Event_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Status.Descriptor instead.
func (Event_Status) EnumDescriptor() ([]byte, []int) {
	return file_sports_sports_proto_rawDescGZIP(), []int{3, 0}
}

// Request for ListEvents call.
type ListEventsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListEventsRequestFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_sports_sports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sports_sports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_sports_sports_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsRequest) GetFilter() *ListEventsRequestFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response to ListEvents call.
type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_sports_sports_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sports_sports_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_sports_sports_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Filter for listing sports events.
type ListEventsRequestFilter struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SportIds []int64                `protobuf:"varint,1,rep,packed,name=sport_ids,json=sportIds,proto3" json:"sport_ids,omitempty"`
	// When unset, include hidden (default). Set false to only visible; true to include hidden.
	ShowHidden *bool `protobuf:"varint,2,opt,name=show_hidden,json=showHidden,proto3,oneof" json:"show_hidden,omitempty"`
	// Order by, e.g. "advertised_start_time" or "advertised_start_time desc" (default asc)
	OrderBy       string `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequestFilter) Reset() {
	*x = ListEventsRequestFilter{}
	mi := &file_sports_sports_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequestFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequestFilter) ProtoMessage() {}

func (x *ListEventsRequestFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sports_sports_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequestFilter.ProtoReflect.Descriptor instead.
func (*ListEventsRequestFilter) Descriptor() ([]byte, []int) {
	return file_sports_sports_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsRequestFilter) GetSportIds() []int64 {
	if x != nil {
		return x.SportIds
	}
	return nil
}

func (x *ListEventsRequestFilter) GetShowHidden() bool {
	if x != nil && x.ShowHidden != nil {
		return *x.ShowHidden
	}
	return false
}

func (x *ListEventsRequestFilter) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// A sports event resource.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID represents a unique identifier for the sports event.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// SportID represents a unique identifier for the sport type.
	SportId int64 `protobuf:"varint,2,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	// Name is the official name given to the sports event.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Venue is the location where the event takes place.
	Venue string `protobuf:"bytes,4,opt,name=venue,proto3" json:"venue,omitempty"`
	// Visible represents whether or not the event is visible.
	Visible bool `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	// AdvertisedStartTime is the time the event is advertised to start.
	AdvertisedStartTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=advertised_start_time,json=advertisedStartTime,proto3" json:"advertised_start_time,omitempty"`
	Status              Event_Status           `protobuf:"varint,7,opt,name=status,proto3,enum=sports.Event_Status" json:"status,omitempty"`
	// HomeTeam represents the home team or participant.
	HomeTeam string `protobuf:"bytes,8,opt,name=home_team,json=homeTeam,proto3" json:"home_team,omitempty"`
	// AwayTeam represents the away team or participant.
	AwayTeam      string `protobuf:"bytes,9,opt,name=away_team,json=awayTeam,proto3" json:"away_team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sports_sports_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sports_sports_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sports_sports_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetSportId() int64 {
	if x != nil {
		return x.SportId
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *Event) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Event) GetAdvertisedStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AdvertisedStartTime
	}
	return nil
}

func (x *Event) GetStatus() Event_Status {
	if x != nil {
		return x.Status
	}
	return Event_STATUS_OPEN
}

func (x *Event) GetHomeTeam() string {
	if x != nil {
		return x.HomeTeam
	}
	return ""
}

func (x *Event) GetAwayTeam() string {
	if x != nil {
		return x.AwayTeam
	}
	return ""
}

var File_sports_sports_proto protoreflect.FileDescriptor

const file_sports_sports_proto_rawDesc = "" +
	"\n" +
	"\x13sports/sports.proto\x12\x06sports\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\x11ListEventsRequest\x127\n" +
	"\x06filter\x18\x01 \x01(\v2\x1f.sports.ListEventsRequestFilterR\x06filter\";\n" +
	"\x12ListEventsResponse\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.sports.EventR\x06events\"\x87\x01\n" +
	"\x17ListEventsRequestFilter\x12\x1b\n" +
	"\tsport_ids\x18\x01 \x03(\x03R\bsportIds\x12$\n" +
	"\vshow_hidden\x18\x02 \x01(\bH\x00R\n" +
	"showHidden\x88\x01\x01\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderByB\x0e\n" +
	"\f_show_hidden\"\xdc\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bsport_id\x18\x02 \x01(\x03R\asportId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05venue\x18\x04 \x01(\tR\x05venue\x12\x18\n" +
	"\avisible\x18\x05 \x01(\bR\avisible\x12N\n" +
	"\x15advertised_start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x13advertisedStartTime\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.sports.Event.StatusR\x06status\x12\x1b\n" +
	"\thome_team\x18\b \x01(\tR\bhomeTeam\x12\x1b\n" +
	"\taway_team\x18\t \x01(\tR\bawayTeam\",\n" +
	"\x06Status\x12\x0f\n" +
	"\vSTATUS_OPEN\x10\x00\x12\x11\n" +
	"\rSTATUS_CLOSED\x10\x012i\n" +
	"\x06Sports\x12_\n" +
	"\n" +
	"ListEvents\x12\x19.sports.ListEventsRequest\x1a\x1a.sports.ListEventsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/list-eventsB\tZ\a/sportsb\x06proto3"

var (
	file_sports_sports_proto_rawDescOnce sync.Once
	file_sports_sports_proto_rawDescData []byte
)

func file_sports_sports_proto_rawDescGZIP() []byte {
	file_sports_sports_proto_rawDescOnce.Do(func() {
		file_sports_sports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sports_sports_proto_rawDesc), len(file_sports_sports_proto_rawDesc)))
	})
	return file_sports_sports_proto_rawDescData
}

var file_sports_sports_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sports_sports_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sports_sports_proto_goTypes = []any{
	(Event_Status)(0),               // 0: sports.Event.Status
	(*ListEventsRequest)(nil),       // 1: sports.ListEventsRequest
	(*ListEventsResponse)(nil),      // 2: sports.ListEventsResponse
	(*ListEventsRequestFilter)(nil), // 3: sports.ListEventsRequestFilter
	(*Event)(nil),                   // 4: sports.Event
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_sports_sports_proto_depIdxs = []int32{
	3, // 0: sports.ListEventsRequest.filter:type_name -> sports.ListEventsRequestFilter
	4, // 1: sports.ListEventsResponse.events:type_name -> sports.Event
	5, // 2: sports.Event.advertised_start_time:type_name -> google.protobuf.Timestamp
	0, // 3: sports.Event.status:type_name -> sports.Event.Status
	1, // 4: sports.Sports.ListEvents:input_type -> sports.ListEventsRequest
	2, // 5: sports.Sports.ListEvents:output_type -> sports.ListEventsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sports_sports_proto_init() }
func file_sports_sports_proto_init() {
	if File_sports_sports_proto != nil {
		return
	}
	file_sports_sports_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sports_sports_proto_rawDesc), len(file_sports_sports_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sports_sports_proto_goTypes,
		DependencyIndexes: file_sports_sports_proto_depIdxs,
		EnumInfos:         file_sports_sports_proto_enumTypes,
		MessageInfos:      file_sports_sports_proto_msgTypes,
	}.Build()
	File_sports_sports_proto = out.File
	file_sports_sports_proto_goTypes = nil
	file_sports_sports_proto_depIdxs = nil
}
